GET http://localhost:5050/authors

####
GET http://localhost:5050/authors/65201a6d4fc256008b345e71

####
POST http://localhost:5050/authors HTTP/1.1
Content-Type: application/json

{
    "nome": "Tizio",
    "cognome": "Roma",
    "email": "tizio@yahoo.com",
    "dataDiNascita": "01 Febbraio 1985",
    "avatar": "Old Guy"
}

####
PATCH http://localhost:5050/authors/65201a6d4fc256008b345e71 HTTP/1.1
Content-Type: application/json

{
    "nome": "Pigrone",
    "cognome": "Della Strada"
}

####
DELETE http://localhost:5050/authors/65201a2f4fc256008b345e6f

####
GET http://localhost:5050/blogPosts

####
GET http://localhost:5050/blogPosts?title=eventi

####
GET http://localhost:5050/blogPosts/6521102342a1cf75b1859440

####
POST http://localhost:5050/blogPosts HTTP/1.1
Content-Type: application/json

{
    "title": "Film Esorcista",
    "category": "Cinema",
    "cover": "Brutto!",
    "readTime": {
        "value": "tre",
        "unit": "min"
    },
    "author": {
        "name": "Tizio",
        "avatar": 10
    },
    "content": "L'esorcista - Il credente è un film del 2023 diretto da David Gordon Green. Il film, sesta pellicola della saga, è il sequel diretto de L'esorcista ed il primo in cui l'attrice Ellen Burstyn riprende il ruolo di Chris MacNeil dopo il primo capitolo."
}

####
PATCH http://localhost:5050/blogPosts/6521115842a1cf75b1859443 HTTP/1.1
Content-Type: application/json

{
    "title": "Eventi fine settimana Roma",
    "category": "Week End"
}

####
DELETE http://localhost:5050/blogPosts/6521124242a1cf75b1859445

